version: '3.8'

services:
  events-prometheus:
    container_name: event-store-prometheus
    image: prom/prometheus:v2.24.0
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  events-grafana:
    container_name: event-store-grafana
    image: grafana/grafana:7.3.7
    volumes:
      - ./monitor/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./monitor/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/dashboard.json"
    ports:
      - "3000:3000"

  events-elasticsearch:
    container_name: event-store-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    volumes:
      - event-store-elasticsearch-local:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9300:9300"
      - "9200:9200"

  events-kibana:
    container_name: event-store-kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://event-store-elasticsearch:9200
    depends_on:
      - events-elasticsearch
    ports:
      - "5601:5601"

volumes:
  event-store-elasticsearch-local:
